install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("lpSolve")
install.packages("lpSolveAPI")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
